# pipelines.yml
################################################################################
# Version: 23.01                                                              #
# Required: Yes                                                                #
# Description: This is a required file for a pfelk installation                #
# This file is where you define your pipelines. You can define multiple.       #
# For more information on multiple pipelines, see the documentation:           #
#   https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html   #
#                                                                              #
################################################################################
#

- pipeline.id: syslog
  path.config: "/etc/syslog/conf.d/*.pfelk"
  pipeline.ecs_compatibility: v8 #Disable if not running Elastic v8+
